# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vjty1CYRS_ZNEHHbJmtPs8EG_95g04TV
"""

pip install streamlit

import streamlit as st

import pandas as pd

!pip install mysql-connector-python

import mysql.connector

import hashlib

def get_connection():
  return mysql.connector.connect(
      host="localhost",
      user="root",
      password = "yourpassword",
      database = "client_query_db"
  )

def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

def register_user(username, password, role):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("SELECT * FROM users WHERE username=%s", (username,))
    if cur.fetchone():
        st.warning("⚠️ Username already exists. Please choose another.")
    else:
        cur.execute(
            "INSERT INTO users (username, hashed_password, role) VALUES (%s, %s, %s)",
            (username, hash_password(password), role)
        )
        conn.commit()
        st.success("✅ Registration successful! Please log in.")
    conn.close()

def login_user(username, password):
    conn = get_connection()
    cur = conn.cursor(dictionary=True)
    cur.execute(
        "SELECT * FROM users WHERE username=%s AND hashed_password=%s",
        (username, hash_password(password))
    )
    user = cur.fetchone()
    conn.close()
    return user

def client_page(username):
    st.title(f"📝 Welcome, {username}")
    st.header("Submit a New Support Query")

    email = st.text_input("Email ID")
    mobile = st.text_input("Mobile Number")
    heading = st.text_input("Query Heading")
    description = st.text_area("Query Description")

    if st.button("Submit Query"):
        if email and mobile and heading and description:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute("""
                INSERT INTO queries (mail_id, mobile_number, query_heading, query_description, status, query_created_time)
                VALUES (%s, %s, %s, %s, %s, %s)
            """, (email, mobile, heading, description, "Open", datetime.now()))
            conn.commit()
            conn.close()
            st.success("✅ Query submitted successfully!")
        else:
            st.warning("⚠️ Please fill all fields before submitting.")

def support_page(username):
    st.title(f"🛠️ Support Dashboard - {username}")

    conn = get_connection()
    df = pd.read_sql("SELECT * FROM queries", conn)
    conn.close()

    st.subheader("📋 Query Overview")
    status_filter = st.selectbox("Filter by Status", ["All", "Open", "Closed"])
    if status_filter != "All":
        df = df[df["status"] == status_filter]

    st.dataframe(df)

    # Close an open query
    open_queries = df[df["status"] == "Open"]
    if not open_queries.empty:
        selected_id = st.selectbox("Select Query ID to Close", open_queries["query_id"])
        if st.button("Close Selected Query"):
            conn = get_connection()
            cur = conn.cursor()
            cur.execute("""
                UPDATE queries
                SET status=%s, query_closed_time=%s
                WHERE query_id=%s
            """, ("Closed", datetime.now(), selected_id))
            conn.commit()
            conn.close()
            st.success(f"✅ Query ID {selected_id} closed successfully!")
    else:
        st.info("No open queries at the moment.")

    # --- Query Insights ---
    st.subheader("📊 Insights & Metrics")

    conn = get_connection()
    df = pd.read_sql("SELECT * FROM queries", conn)
    conn.close()

    st.write("### Query Status Distribution")
    st.bar_chart(df["status"].value_counts())

    if "query_closed_time" in df.columns:
        df["query_created_time"] = pd.to_datetime(df["query_created_time"])
        df["query_closed_time"] = pd.to_datetime(df["query_closed_time"])
        df["resolution_time_hrs"] = (
            (df["query_closed_time"] - df["query_created_time"]).dt.total_seconds() / 3600
        )
        avg_res_time = round(df["resolution_time_hrs"].mean(), 2)
        st.metric("⏱️ Average Resolution Time (hrs)", avg_res_time if not pd.isna(avg_res_time) else 0)

def login_register_page():
    st.title("🔐 Client Query Management System")

    tab1, tab2 = st.tabs(["🔑 Login", "🧾 Register"])

    with tab1:
        username = st.text_input("Username", key="login_user")
        password = st.text_input("Password", type="password", key="login_pass")
        if st.button("Login"):
            user = login_user(username, password)
            if user:
                st.session_state["username"] = user["username"]
                st.session_state["role"] = user["role"]
                st.experimental_rerun()
            else:
                st.error("❌ Invalid credentials. Please try again.")

    with tab2:
        username = st.text_input("Create Username", key="reg_user")
        password = st.text_input("Create Password", type="password", key="reg_pass")
        role = st.selectbox("Role", ["Client", "Support"])
        if st.button("Register"):
            if username and password:
                register_user(username, password, role)
            else:
                st.warning("⚠️ Please enter username and password.")

def main():
    st.set_page_config(page_title="Client Query Management System", layout="wide")

    if "username" not in st.session_state:
        login_register_page()
    else:
        role = st.session_state["role"]
        username = st.session_state["username"]

        st.sidebar.title("Navigation")
        if st.sidebar.button("Logout"):
            st.session_state.clear()
            st.experimental_rerun()

        if role.lower() == "client":
            client_page(username)
        elif role.lower() == "support":
            support_page(username)
        else:
            st.error("Invalid user role detected!")

if __name__ == "__main__":
    main()

!pip install streamlit

from google.colab import files
uploaded = files.upload()

import streamlit as st

def main():
    st.set_page_config(page_title="Client Query Management System", layout="wide")

    if "username" not in st.session_state:
        login_register_page()
    else:
        role = st.session_state["role"]
        username = st.session_state["username"]

        st.sidebar.title("Navigation")
        if st.sidebar.button("Logout"):
            st.session_state.clear()
            st.experimental_rerun()

        if role.lower() == "client":
            client_page(username)
        elif role.lower() == "support":
            support_page(username)
        else:
            st.error("Invalid user role detected!")

if __name__ == "__main__":
    main()